### ISSUE TITLE
Why not submit some packages, like the updated Lumina Desktop, to the AUR proper?

### ISSUE THREAD

**Issue by marek-lach** [polaur/aur-rebased#2]
It'd be very useful.

**Comment by pavbaranov** [comment]
It's quite simple. There's somebody on AUR who is maintainer of lumina-destkop. I don't want to be a maintainer of this package in AUR. There's a comment: https://aur.archlinux.org/packages/lumina-desktop#comment-730208 with link to updated Lumina DE, so the maintainer of this can easily update his PKGBUILD.
POLAUR is very simple to use when you decided to install and use our pak (or pak-git) utility. Just do:
1. mkdir -p pak && cd pak
2. wget https://raw.githubusercontent.com/polaur/new-branded/master/pak/PKGBUILD
3. wget https://raw.githubusercontent.com/polaur/new-branded/master/pak/CHANGELOD
4. makepkg -sirc
Since this utility has installed in your system you can browse and build packages from POLAUR, too (pak is also pacman and AUR wrapper). Just do (i.e. for lumina-desktop):
pak - P aur-rebased/lumina-desktop
And enjoy.
There are several reasons why we maintain POLAUR and not participated in AUR, rather.

**Comment by marek-lach** [comment]
Oh! A very nice explanation. Thanks!
